# Derived from https://github.com/theochem/qcgrids/blob/master/.travis.yml
env:
  matrix:
  - MYCONDAPY=2.7

####
# EVERYTHING BELOW THIS LINE WILL BE COPIED INTO OTHER YMLs
####

# Do not use Travis Python to save some time.
language: generic
os:
- linux
- osx
osx_image: xcode6.4
dist: trusty
sudo: false

matrix:
  # We only test on Linux with one specific Python version, unless we make a release. All
  # other cases are allowed to fail and will exit early. With the fast_finish option,
  # travis will send a status update to github as soon as the non-allowed-to-fail has
  # finished. This speeds up testing in PRs.
  #
  # This is not ideal. It would be better to run just one item from the build matrix when
  # not preparing a release. This is not possible on Travis. There are several tickets on
  # travis-ci related to this limitation.
  #
  #    https://github.com/travis-ci/travis-ci/issues/7451
  #    https://github.com/travis-ci/travis-ci/issues/7149
  #    https://github.com/travis-ci/travis-ci/issues/2778
  #    ...
  fast_finish: true
  allow_failures:
  - osx

cache:
  directories:
  - $HOME/download
  - $HOME/miniconda

before_cache:
- if ! [[ $TRAVIS_TAG ]]; then rm -rf $HOME/miniconda/conda-bld; fi
- rm -rf $HOME/pychimera $HOME/miniconda/locks $HOME/miniconda/pkgs $HOME/miniconda/var $HOME/miniconda/conda-meta/history
- conda remove --force gaudi

branches:
  only:
  - master
  - /^[0-9]+\.[0-9]+(\.[0-9]+)?([ab][0-9]*)?$/  # release branches

before_install:
# Get miniconda. Take the right version, so re-installing python is hopefully not needed.
- if test -e $HOME/miniconda/bin; then
    echo "miniconda already installed.";
  else
    echo "Installing miniconda.";
    rm -rf $HOME/miniconda;
    mkdir -p $HOME/download;
    if [[ -d $HOME/download/miniconda.sh ]]; then rm -rf $HOME/download/miniconda.sh; fi;
    if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O $HOME/download/miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O $HOME/download/miniconda.sh;
    fi;
    bash $HOME/download/miniconda.sh -b -p $HOME/miniconda;
  fi
# Configure conda and get a few essentials
- source $HOME/miniconda/bin/activate
- hash -r
- conda config --set always_yes yes
- conda install -q conda conda-build
- pip install -U pytest pytest-benchmark
# Show conda info for debugging
- conda info -a
# Get Chimera
- git clone https://github.com/insilichem/pychimera.git $HOME/pychimera;
- if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
    if [[ ! -e $HOME/miniconda/bin/chimera ]]; then
      conda build -q $HOME/pychimera/conda-recipes/ucsf-chimera-headless;
      conda install -y -c $HOME/miniconda/conda-bld ucsf-chimera-headless;
      ln -s $HOME/miniconda/bin/chimera-headless $HOME/miniconda/bin/chimera || true;
    fi;
  else
    if [[ ! -e $HOME/chimera/Chimera.app/Contents/Resources/bin/chimera ]]; then
        set +x;
        echo "IMPORTANT - By downloading you accept the UCSF Chimera Non-Commercial Software License Agreement!";
        echo "IMPORTANT - The license agreement can be found at http://www.cgl.ucsf.edu/chimera/license.html";
        echo "IMPORTANT - If you do not agree, please press Ctrl-C now.";
        echo "IMPORTANT - Downloading in 10 seconds...'";
        sleep 10;
        set -x;
        _file="chimera-1.12-mac64.dmg";
        _filepath="mac64/${_file}";
        _downloader="https://www.rbvi.ucsf.edu/chimera/cgi-bin/secure/chimera-get.py";
        _download=`curl -s -F file="${_filepath}" -F choice=Accept "${_downloader}" | grep href | sed -E 's/.*href="(.*)">/\1/'`;
        curl "https://www.rbvi.ucsf.edu""${_download}" -o "${_file}";
        hdiutil convert "${_file}" -format UDRW -o chimerarw;
        hdiutil attach -mountpoint "$HOME/chimera" chimerarw.dmg;
        rm -rf $HOME/chimera/Chimera.app/Contents/Resources/lib/python2.7/site-packages/setuptools*;
        pip install -U setuptools -t $HOME/chimera/Chimera.app/Contents/Resources/lib/python2.7/site-packages;
    fi;
    export CHIMERADIR="$HOME/chimera/Chimera.app/Contents/Resources";
  fi


install:
# Dependencies
- conda build -q -c insilichem -c omnia -c salilab -c bioconda conda-recipe
- conda install -y --use-local -c insilichem -c omnia -c salilab -c bioconda gaudi
# Show currently installed packages
- conda list

script:
- cd tests
- python run_test.py
- cd ..

before_deploy:
- conda install anaconda-client

deploy:
  # Deploy to Anaconda.org
  - provider: script
    script: anaconda -t $ANACONDA_TOKEN upload -u insilichem $HOME/miniconda/conda-bld/**/gaudi-*.tar.bz2
    skip_cleanup: true
    on:
      tags: true