name: gaudi
channels:
- insilichem
- omnia
dependencies:
- python=2.7
- nomkl
- openmm
- openmoltools
- pdbfixer
- cclib
- scipy
- git
- pip:
  - pychimera
  - munch
  - voluptuous
  - click
  - boltons
  - deap
  - pyyaml
  - prody
  - git+https://bitbucket.org/insilichem/gaudi

