package:
  name: gaudi
  version: {{ '{}{}{}'.format(environ['GIT_DESCRIBE_TAG'][1:], 
                              (('+' + environ['GIT_DESCRIBE_NUMBER']) if environ['GIT_DESCRIBE_NUMBER'] else ''),
                              (('.' + environ['GIT_DESCRIBE_HASH']) if environ['GIT_DESCRIBE_HASH'] else '')) 
           }}

about:
  home: https://github.com/insilichem/gaudi
  license: Apache 2.0
  summary: Genetic Algorithms with Unrestricted Descriptors for Intuitive Molecular Modeling

source:
  git_url: https://github.com/insilichem/gaudi.git
  git_tag: {{ environ['GIT_DESCRIBE_TAG'] }}

requirements:
  build:
    - python 2.7*
    - setuptools
    - distribute

  run:
    - python 2.7*
    - nomkl
    - openmm
    - openmoltools
    - pdbfixer
    - cclib
    - scipy
    - imp

test:
  imports:
    - gaudi



