package:
  name: gaudi
  version: {{ '{}{}{}'.format(environ['GIT_DESCRIBE_TAG'][1:], 
                               (('+' + environ['GIT_DESCRIBE_NUMBER']) if environ['GIT_DESCRIBE_NUMBER'] else ''),
                               (('.' + environ['GIT_DESCRIBE_HASH']) if environ['GIT_DESCRIBE_HASH'] else '')
                              ) }}

about:
  home: https://bitbucket.org/insilichem/gaudi
  license: Free For Educational Use
  summary: "Genetic Algorithms for Universal Design Inference"

source:
  path: ../

requirements:
  build:
    - python 2.7*

  run:
    - python 2.7*
    - pip
    - pychimera
    - openmm
    - openmoltools
    - pdbfixer
    - cclib
    - scipy

test:
 
  imports:
    - gaudi



