package:
  name: gaudi
  version: "0.0.1"

about:
  home: https://bitbucket.org/jrgp/gaudi
  license: Free For Educational Use
  summary: "Genetic Algorithms for Universal Design Inference and Atomic Scale Modeling"

source:
  path: ../

requirements:
  build:
    - python 2.7*

  run:
    - python 2.7*
    - pychimera
    - deap
    - pyyaml
    - click
    - repoze.lru
    - openmm
    - openmoltools
    - pdbfixer
    # - pip:
    #   - munch
    #   - voluptuous

test:
  imports:
    - gaudi
